"""Данные и эталоны девяти контрольных сценариев демонстрационного набора."""

from datetime import date
from decimal import Decimal

from app.demo_data.scenario_models import DemoScenario

# Девять стабильных демонстрационных сценариев по таблице design.md
DEMO_SCENARIOS: list[DemoScenario] = [
    # 1. oil-quarter-plan: Целевой вопрос о масле
    DemoScenario(
        id="oil-quarter-plan",
        name="Квартальный план закупки массажного масла",
        goal="Расход, остаток, закупка, цена, стоимость, дата и бюджет",
        method="POST",
        path="/api/procurement/plan",
        json_body={"as_of": "2026-09-29", "horizon_months": 3},
        selector={"sku": "DEMO-OIL", "location": "DEMO-MS-01"},
        expected={
            "sku": "DEMO-OIL",
            "location": "DEMO-MS-01",
            "order_date": date(2026, 11, 11),
            "delivery_date": date(2026, 11, 18),
            "quantity": Decimal("30.000"),
            "unit_price": Decimal("100.00"),
            "total_cost": Decimal("3000.00"),
            "average_daily_consumption": Decimal("1.000000"),
            "initial_stock": Decimal("50.000"),
            "budget_known_total": Decimal("20300.00"),
            "sku_budget_total": Decimal("4500.00"),
            "sku_budget_quantity": Decimal("45.000"),
        },
        forecast_expected={
            "sku": "DEMO-OIL",
            "location": "DEMO-MS-01",
            "current_stock": Decimal("50.000"),
            "available_stock": Decimal("50.000"),
            "average_daily_consumption": Decimal("1.000000"),
            "recommended_qty": Decimal("45.000"),
            "unit_price": Decimal("100.00"),
            "total_cost": Decimal("4500.00"),
            "order_date": date(2026, 11, 11),
            "days_count": 91,
        },
        stock_expected={
            "sku": "DEMO-OIL",
            "location": "DEMO-MS-01",
            "current_stock": Decimal("50.000"),
            "available_stock": Decimal("50.000"),
            "expired_stock": Decimal("0.000"),
            "average_daily_consumption": Decimal("1.000000"),
            "days_of_stock": Decimal("50.0"),
            "nearest_expiry_date": date(2027, 3, 28),
        },
    ),
    # 2. lead-time-stockout: Запас закончится до поставки
    DemoScenario(
        id="lead-time-stockout",
        name="Дефицит запаса до возможной даты поставки",
        goal="Запас закончится до поставки: stockout, дата исчерпания и дни дефицита",
        method="GET",
        path="/api/alerts",
        params={"as_of": "2026-09-29", "limit": 100},
        selector={"sku": "DEMO-DEFICIT", "location": "DEMO-MS-02", "type": "stockout"},
        expected={
            "sku": "DEMO-DEFICIT",
            "location": "DEMO-MS-02",
            "type": "stockout",
            "level": "critical",
            "available_stock": Decimal("5.000"),
            "average_daily_consumption": Decimal("1.000000"),
            "lead_time_days": 10,
            "days_of_stock": Decimal("5.0"),
            "stockout_date": date(2026, 10, 4),
            "shortage_days": 5,
        },
    ),
    # 3. expiry-and-writeoff: Годного запаса больше расхода до срока
    DemoScenario(
        id="expiry-and-writeoff",
        name="Приближение срока годности и риск списания",
        goal="Годного запаса больше расхода: expiring_soon, writeoff_risk и объём",
        method="GET",
        path="/api/alerts",
        params={"as_of": "2026-09-29", "limit": 100},
        selector={"sku": "DEMO-EXPIRY", "location": "DEMO-MS-01", "type": "writeoff_risk"},
        expected={
            "sku": "DEMO-EXPIRY",
            "location": "DEMO-MS-01",
            "type": "writeoff_risk",
            "level": "warning",
            "expected_writeoff_qty": Decimal("29.444"),
            "horizon_days": 30,
            "horizon_end": date(2026, 10, 29),
            "expiring_soon_type": "expiring_soon",
            "expiring_soon_level": "warning",
            "expiring_soon_days_until_expiry": 5,
            "expiring_soon_expiry_date": date(2026, 10, 4),
            "expiring_soon_batch_number": "DEMO-BATCH-EXPIRY",
        },
    ),
    # 4. expired-stock: Просрочка остаётся в учётном остатке
    DemoScenario(
        id="expired-stock",
        name="Просроченный остаток на складе",
        goal="Просрочка остаётся в учётном остатке: expired, учётный и доступный остатки",
        method="GET",
        path="/api/stock",
        params={"limit": 100},
        selector={"sku": "DEMO-EXPIRED", "location": "DEMO-MS-01"},
        expected={
            "sku": "DEMO-EXPIRED",
            "location": "DEMO-MS-01",
            "current_stock": Decimal("10.000"),
            "available_stock": Decimal("0.000"),
            "expired_stock": Decimal("10.000"),
            "average_daily_consumption": Decimal("0.000000"),
            "days_of_stock": None,
            "nearest_expiry_date": None,
            "alert_type": "expired",
            "alert_level": "critical",
            "alert_expired_quantity": Decimal("10.000"),
        },
    ),
    # 5. no-movement: Нет движения дольше порога
    DemoScenario(
        id="no-movement",
        name="Отсутствие складского движения",
        goal="Нет движения дольше порога: no_movement и нулевая закупка",
        method="GET",
        path="/api/alerts",
        params={"as_of": "2026-09-29", "limit": 100},
        selector={"sku": "DEMO-IDLE", "location": "DEMO-MS-01", "type": "no_movement"},
        expected={
            "sku": "DEMO-IDLE",
            "location": "DEMO-MS-01",
            "type": "no_movement",
            "level": "info",
            "current_stock": Decimal("10.000"),
            "no_movement_days_threshold": 90,
            "plan_items_count": 0,
        },
    ),
    # 6. short-history: История короче 90 дней
    DemoScenario(
        id="short-history",
        name="Неполная история расхода",
        goal="История короче 90 дней: incomplete_history, знаменатель 90 и число дней",
        method="POST",
        path="/api/forecast",
        json_body={
            "sku": "DEMO-SHORT",
            "location": "DEMO-MS-02",
            "as_of": "2026-09-29",
            "horizon_months": 3,
        },
        expected={
            "sku": "DEMO-SHORT",
            "location": "DEMO-MS-02",
            "is_history_complete": False,
            "history_days": 10,
            "history_denominator": 90,
            "average_daily_consumption": Decimal("0.011111"),
            "recommended_qty": Decimal("0.000"),
            "total_cost": Decimal("0.00"),
            "alert_type": "incomplete_history",
            "alert_required_days": 90,
            "alert_history_days": 10,
        },
    ),
    # 7. unknown-price: Есть потребность, нет цены
    DemoScenario(
        id="unknown-price",
        name="Потребность в закупке без известной цены",
        goal="Есть потребность, нет цены: количество есть, цена null, бюджет неполон",
        method="POST",
        path="/api/procurement/plan",
        json_body={"as_of": "2026-09-29", "horizon_months": 3},
        selector={"sku": "DEMO-NOPRICE", "location": "DEMO-MS-01"},
        expected={
            "sku": "DEMO-NOPRICE",
            "location": "DEMO-MS-01",
            "quantity": Decimal("32.000"),
            "unit_price": None,
            "total_cost": None,
            "budget_is_price_complete": False,
            "budget_unknown_price_count": 1,
        },
    ),
    # 8. unknown-lead-time: Есть потребность, нет условий
    DemoScenario(
        id="unknown-lead-time",
        name="Потребность в закупке без закупочных условий",
        goal="Есть потребность, нет условий: недатированная оценка и неполнота",
        method="POST",
        path="/api/procurement/plan",
        json_body={"as_of": "2026-09-29", "horizon_months": 3},
        selector={"sku": "DEMO-NOLEAD", "location": "DEMO-MS-01"},
        expected={
            "sku": "DEMO-NOLEAD",
            "location": "DEMO-MS-01",
            "is_undated": True,
            "order_date": None,
            "quantity": Decimal("86.000"),
            "unit_price": None,
            "total_cost": None,
            "undated_items_count": 1,
            "undated_total_quantity": Decimal("86.000"),
            "incompleteness_reason_keyword": "Неизвестное плечо поставки",
            "warning_keyword": "LEAD_TIME_UNKNOWN",
        },
    ),
    # 9. incoming-order: Заказ уже в пути
    DemoScenario(
        id="incoming-order",
        name="Учёт оформленного ожидаемого заказа",
        goal="Заказ уже в пути: поставка в исходных данных и нет дубля закупки",
        method="POST",
        path="/api/procurement/plan",
        json_body={"as_of": "2026-09-29", "horizon_months": 3},
        selector={"sku": "DEMO-INCOMING", "location": "DEMO-MS-01"},
        expected={
            "existing_order_doc": "DEMO-PO-INCOMING",
            "existing_order_qty": Decimal("20.000"),
            "existing_order_date": date(2026, 9, 30),
            "first_order_date": date(2026, 10, 17),
            "first_order_quantity": Decimal("31.000"),
        },
    ),
]
