FROM nginx:alpine

COPY web/nginx.conf /etc/nginx/conf.d/default.conf
COPY web/index.html /usr/share/nginx/html/index.html
COPY web/styles.css /usr/share/nginx/html/styles.css
COPY web/js/ /usr/share/nginx/html/js/

EXPOSE 80
